version: "3.5"
services:
  postgres:
    image: "postgres:12"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ganadero2022
    volumes:
      - ./conf/postgres/initdb/:/docker-entrypoint-initdb.d/
    networks:
      - interdb
  pgAdmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ganadero@ucb.edu.bo
      PGADMIN_DEFAULT_PASSWORD: ganadero2022
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/conf/server.json
    volumes:
      - ./conf/pgadmin/:/pgadmin4/conf/
    networks:
      - interdb
networks:
  default:
    name: ganadero_default
    driver: bridge
  interdb:
    name: ganadero_interdb
    driver: bridge

